---
##
# Installs oracle java.
#

- name: Adding Java PPA Repository
  apt_repository: repo=ppa:webupd8team/java

- name: Adding debconf entry for Java installer
  # Previously working shell command:
  # action: shell echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  debconf: name={{ java_apt_oracle_installer_package }} question='lshared/accepted-oracle-license-v1-1' value=true vtype=boolean

- name: Installing Java
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items: "{{ java_apt_packages_oracle }}"
