---
##
# Installs oracle java.
#

- name: Adding Java PPA Repository
  apt_repository: repo=ppa:webupd8team/java

- name: Adding debconf entry for Java installer
  shell: echo {{ java_apt_oracle_installer_package }} shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  changed_when: false

- name: Installing Java
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items: "{{ java_apt_packages_oracle }}"
