---
##
# Installs oracle java.
#

- name: Java | Adding Java PPA Repository
  action: apt_repository repo=ppa:webupd8team/java

- name: Java | Adding debconf entry for Java installer
  # Previously working shell command:
  # action: shell echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  debconf: name=oracle-java7-installer question='lshared/accepted-oracle-license-v1-1' value=true vtype=boolean

- name: Java | Installing Java
  apt: pkg={{ item }} state=latest
  with_items:
    - oracle-java7-installer
    - oracle-java7-set-default