---
- name: "Add default variables per distribution"
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_distribution_release }}.yml"
  check_mode: no

- include: "java_openjdk.yml"
  tags: "java"
  when: java_openjdk

- include: "java_oracle.yml"
  tags: "java"
  when: not java_openjdk

